<?php

require_once '../../config/Database.php';
require_once '../../tools/tools.php';
require_once '../../Entity/User.php';
require_once '../../Model/UserModel.php';



$user_model = new UserModel();


if($_POST){

    //pre_var_dump($_POST,null, true);
    if (isset($_POST['email']) && !empty($_POST['email'])) {
        if(isset($_POST['password']) && !empty($_POST['password'])){
            if(isset($_POST['password_verif']) && !empty($_POST['password_verif'])){
                
                $email          = $_POST['email'];
                $password       = $_POST['password'];
                $password_verif = $_POST['password_verif'];

                $one_user = $user_model->connexion($email, $password, $password_verif);
            }
        }
    }
}




?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="../../js/jquery-3.5.1.min.js"></script>
    <script src="../../js/jquery.js"></script>
    <script src="../../js/jquery.validate.min.js" ></script>    
    <script src="../../js/validation.js"></script>
    <title>Connexion</title>
</head>
<body>
    <div>
        <a href="../../index.phtml">Retoure à l'accueil</a>
        <h2>Connexion</h2>

        <div id="error">
            <span></span>
        </div>
        <form action="" method="post" id="form_connexion_user">

            <div>
                <label for="email">email</label>
                <div>
                    <input type="email" name="email" id="email" required>
                <div>
            </div>

            <div>
                <label for="password">mot de passe</label>
                <div>
                    <input type="password" name="password" id="password" minlength="2" required>
                <div>
            </div>

            <div>
                <label for="password_verif">confirmez le mot de passe</label>
                <div>
                    <input type="password" name="password_verif" id="password_verif" required>
                <div>
            </div>

            <div>
                <input type="submit" value="Envoyer">
            </div>
        </form>
    </div>
</body>
</html>